service: wiki-python

plugins:
  - serverless-python-requirements

# Load .env file
useDotenv: true

provider:
  name: aws
  runtime: python3.8
  region: eu-west-3

custom:
  pythonRequirements:
    # Dockerize pip will install dependencies in a docker simulating the lambda environment
    dockerizePip: true

# Do not include node_modules, venv, and test files in the lambda zip
package:
  exclude:
    - node_modules/**
    - venv/**
    - test/**

functions:
  wiki-python:
    handler: main.handler
    environment:
      # AWS
      AWS_SECRET_ACCESS_KEY: ${{env:AWS_SECRET_ACCESS_KEY}}
      AWS_ACCESS_KEY_ID: ${{env:AWS_ACCESS_KEY_ID}}
      AWS_DEFAULT_REGION: ${{env:AWS_DEFAULT_REGION}}
      # RDS
      SQL: ${{env:SQL}}
      HOST: ${{env:HOST}}
      PORT: ${{env:PORT}}
      USERNAME: ${{env:USERNAME}}
      PASSWORD: ${{env:PASSWORD}}
      DATABASE: ${{env:DATABASE}}
